#!/usr/bin/env bash
# research-gate.sh — PreToolUse hook for Prism
# Fires on Write tool calls for new files. Checks that research was logged
# in history.jsonl (after the most recent session_start marker) before
# allowing new file creation.
#
# Skips: .prism/* files, CLAUDE.md, and files that already exist (edits).
# Returns {"permissionDecision":"deny","message":"..."} to block, or {} to allow.
set -uo pipefail

INPUT=$(cat)

# Only active when Prism is running
if [ ! -d ".prism" ]; then
  echo '{}'
  exit 0
fi

# Only fire on Write tool
TOOL_NAME=$(printf '%s' "$INPUT" | python3 -c 'import sys,json; print(json.loads(sys.stdin.read()).get("tool_name",""))' 2>/dev/null || true)

if [ "$TOOL_NAME" != "Write" ]; then
  echo '{}'
  exit 0
fi

# Extract file path
FILE_PATH=$(printf '%s' "$INPUT" | python3 -c 'import sys,json; print(json.loads(sys.stdin.read()).get("tool_input",{}).get("file_path",""))' 2>/dev/null || true)

if [ -z "$FILE_PATH" ]; then
  echo '{}'
  exit 0
fi

# Skip .prism/* files (internal bookkeeping)
case "$FILE_PATH" in
  *.prism/*|*/.prism/*)
    echo '{}'
    exit 0
    ;;
esac

# Skip CLAUDE.md (auto-generated by guardrail 6)
case "$FILE_PATH" in
  */CLAUDE.md|CLAUDE.md)
    echo '{}'
    exit 0
    ;;
esac

# Skip if file already exists (this is an edit/overwrite, not new creation)
if [ -f "$FILE_PATH" ]; then
  echo '{}'
  exit 0
fi

# Check history.jsonl for research entries after most recent session_start
HISTORY=".prism/history.jsonl"
if [ ! -f "$HISTORY" ]; then
  jq -n --arg msg "[prism] RESEARCH GATE: You are creating a new file but no research has been logged this session. Before creating new files, run the Research Gate (Guardrail 7): research at least 2 approaches, present options to the founder, and log the research to history.jsonl." '{"permissionDecision":"deny","message":$msg}'
  exit 0
fi

# Find the line number of the most recent session_start
LAST_START_RAW=$(grep -n '"session_start"' "$HISTORY" 2>/dev/null | tail -1 | cut -d: -f1)
LAST_START=${LAST_START_RAW:-0}
LAST_START=$(echo "$LAST_START" | tr -d '[:space:]')

# Check for research or pure-local entries after that line
if [ "$LAST_START" -gt 0 ] 2>/dev/null; then
  RESEARCH_COUNT=$(tail -n +"$LAST_START" "$HISTORY" | grep -c '"research"\|"pure-local"' 2>/dev/null || echo "0")
else
  RESEARCH_COUNT=$(grep -c '"research"\|"pure-local"' "$HISTORY" 2>/dev/null || echo "0")
fi
RESEARCH_COUNT=$(echo "$RESEARCH_COUNT" | tr -d '[:space:]')

if [ "${RESEARCH_COUNT:-0}" -eq 0 ]; then
  # Log the violation
  jq -n --arg action "hook_violation" --arg hook "research-gate" \
    --arg file "$FILE_PATH" --arg ts "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
    '{action: $action, ts: $ts, hook: $hook, file: $file}' \
    >> "$HISTORY" 2>/dev/null || true

  jq -n --arg msg "[prism] RESEARCH GATE: You are creating a new file ($FILE_PATH) but no research has been logged this session. Before creating new files with external dependencies, run the Research Gate (Guardrail 7): research at least 2 approaches, present options to the founder, and log the research to history.jsonl. If this is a pure-local file with no external deps, log a pure-local entry first." '{"permissionDecision":"deny","message":$msg}'
  exit 0
fi

echo '{}'
